title: Amy's Cookbook
description: A personal cookbook of tested recipes.
baseurl: "/Cookbook"
url: "https://ridiculous2d.github.io"

markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

exclude:
  - dev
  - README.md
